# Generated by Django 6.0.6 on 2026-07-04 00:41

import django.db.models.deletion
import generate_sbom.manifests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_orgapikey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManifestUpload",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to=generate_sbom.manifests.models.manifest_upload_path)),
                (
                    "detected_format",
                    models.CharField(
                        choices=[
                            ("requirements", "requirements.txt"),
                            ("pyproject", "pyproject.toml"),
                            ("pixi_lock", "pixi.lock"),
                            ("pixi_toml", "pixi.toml"),
                            ("conda", "conda environment.yml"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("application_id", models.CharField(max_length=255)),
                ("component_name", models.CharField(max_length=255)),
                ("repository_url", models.URLField(max_length=500)),
                ("source_branch", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="users.org"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifest_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
