# Generated by Django 6.0.6 on 2026-08-19 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_seed_default_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=32)),
                ("ordinal", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=200)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="inventory.sbomjob"
                    ),
                ),
            ],
            options={
                "ordering": ("ordinal",),
                "constraints": [models.UniqueConstraint(fields=("job", "key"), name="uniq_job_task_key")],
            },
        ),
    ]
