# Generated by Django 6.0.6 on 2026-07-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_orgapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="is_admin_org",
            field=models.BooleanField(default=False),
        ),
    ]
