# Generated by Django 6.0.6 on 2026-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisreport",
            name="report_type",
            field=models.CharField(
                choices=[("vuln", "Vulnerability"), ("license", "License"), ("version", "Version currency")],
                max_length=10,
            ),
        ),
    ]
