# Generated by Django 6.0.6 on 2026-07-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sbom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("vuln", "Vulnerability"),
                            ("license", "License"),
                            ("graph", "Dependency graph"),
                            ("version", "Version currency"),
                        ],
                        max_length=10,
                    ),
                ),
                ("artifact_key", models.CharField(blank=True, max_length=500, null=True)),
                ("summary", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("failed", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="sbom.sbomjob"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("job", "report_type"), name="uniq_job_report_type")],
            },
        ),
    ]
